export type Roles =
    'ROLE_ADMIN' |
    'ROLE_REGISTRATION_PARAMETER' |
    'ROLE_REGISTRATION_USER' |
    'ROLE_REGISTRATION_GROUP' |
    'ROLE_REGISTRATION_UNITY' |
    'ROLE_REGISTRATION_PRODUCT' |
    'ROLE_REGISTRATION_SECTOR' |
    'ROLE_REGISTRATION_EMPLOYEE' |
    'ROLE_REGISTRATION_LABORCOSTTYPE' |
    'ROLE_REGISTRATION_OPERATIONALCOSTTYPE' |
    'ROLE_REGISTRATION_OCCURRENCE' |
    'ROLE_REGISTRATION_STATUSPALLET' |
    'ROLE_FORMULATION' |
    'ROLE_PRODUCTION' |
    'ROLE_STOCK' |
    'ROLE_LABOR_PAYMENT' |
    'ROLE_OPERATIONAL_PAYMENT' |
    'ROLE_COST_CALCULATION'



