INSERT INTO tb_user (name,email,password) VALUES ('Diego Wandrofski Borges','diego@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_USER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);

INSERT INTO tb_unity(id,description)VALUES('UN','UNIDADE');
INSERT INTO tb_unity(id,description)VALUES('KG','KILO');
INSERT INTO tb_unity(id,description)VALUES('L','LITRO');
INSERT INTO tb_unity(id,description)VALUES('CX','CAIXA');

INSERT INTO tb_group(name)VALUES('INSUMO');
INSERT INTO tb_group(name)VALUES('MATERIA PRIMA');
INSERT INTO tb_group(name)VALUES('EMBALAGEM');
INSERT INTO tb_group(name)VALUES('USO E CONSUMO');
INSERT INTO tb_group(name)VALUES('PRODUTO ACABADO');

INSERT INTO tb_SECTOR(NAME) VALUES('PRODUCAO');
INSERT INTO tb_SECTOR(NAME) VALUES('FRACIONAMENTO');
INSERT INTO tb_SECTOR(NAME) VALUES('CALDEIRA');

INSERT INTO tb_OCCURRENCE(NAME) VALUES('NORMAL');
INSERT INTO tb_OCCURRENCE(NAME) VALUES('ALTERACAO NA QUANTIDADE PRODUZIDA');
INSERT INTO tb_OCCURRENCE(NAME) VALUES('PERDA NA PRODUÇÃO');
INSERT INTO tb_OCCURRENCE(NAME) VALUES('EMBALAGEM DANIFICADA');
INSERT INTO tb_OCCURRENCE(NAME) VALUES('INSUMO DANIFICADO');
INSERT INTO tb_OCCURRENCE(NAME) VALUES('MATERIA PRIMA FORA DO PADRÃO');

INSERT INTO tb_LABOR_COST_TYPE (NAME) VALUES('SALARIO');
INSERT INTO tb_LABOR_COST_TYPE (NAME) VALUES('HORA EXTRA');
INSERT INTO tb_LABOR_COST_TYPE (NAME) VALUES('AUXILIO TRANSPORTE');

INSERT INTO tb_APPORTIONMENT_TYPE (NAME,TYPE) VALUES('ENERGIA ELETRICA',1);
INSERT INTO tb_APPORTIONMENT_TYPE (NAME,TYPE) VALUES('LIMPEZA',0);
INSERT INTO tb_APPORTIONMENT_TYPE (NAME,TYPE) VALUES('AGUA',0); 

INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Leite in natura',1.032,'LEITE IN NATURA',1.032,'',2,'L',0);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Leite in natura desnatado',1.032,'LEITE IN NATURA DESNATADO',1.032,'',2,'L',0);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Saco utilizado para envase de leite em pó da marca Moinho',0.700,'SACO MOINHO 25 KG',0.700,'',3,'UN',0);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Saco utilizado para envase de leite em pó',0.700,'SACO 25 KG PARDO',0.700,'',3,'UN',0);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Abraçadeira utilizada para vedar o saco interno de leite',0.1,'ABRACADEIRA DE NYLON',0.1,'',3,'UN',0);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Linha de poliester utilizada para para costurar a embalagem externa',1,'LINHA DE POLIESTER',1,'',3,'KG',0);  
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Leite em pó integral',1,'LEITE EM PO',1,'SC COM 25KG',5,'KG',365);
INSERT INTO tb_product(description, gross_weight,name,net_weight,packaging,line_id,unity_id,validity_days)VALUES('Leite em pó integral desnatado',1,'LEITE EM PO DESNATADO',1,'SC COM 25KG',5,'KG',365);

INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-01T20:50:07.12345Z','',0,5,1,1.20,50000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-10T20:50:07.12345Z','',0,5,1,1.25,10000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-15T20:50:07.12345Z','',0,5,1,1.05,100500,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-25T20:50:07.12345Z','',0,5,1,1.35,5000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-05T20:50:07.12345Z','',0,5,2,0.90,1000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-10T20:50:07.12345Z','',0,5,2,0.91,500,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-16T20:50:07.12345Z','',0,5,2,0.93,1500,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-26T20:50:07.12345Z','',0,5,2,0.95,100,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-05T20:50:07.12345Z','',0,5,3,0.90,1000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-10T20:50:07.12345Z','',0,5,3,0.91,500,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-16T20:50:07.12345Z','',0,5,3,0.93,1500,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-30T20:50:07.12345Z','',0,5,3,0.95,100,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-02T20:50:07.12345Z','',0,5,4,0.15,1000,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-05T20:50:07.12345Z','',0,5,4,0.13,100,0);
INSERT INTO tb_STOCK_MOVEMENT(date,description,id_orign_movement,type,product_id,cost,entry,out)VALUES(TIMESTAMP WITH TIME ZONE '2021-04-05T20:50:07.12345Z','',0,5,5,19,100,0);


INSERT INTO tb_FORMULATION (COEFFICIENT,DESCRIPTION,PRODUCT_ID) VALUES(1000,'LEITE EM PO',7);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(1,1,8400,0,0,1);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(1,3,40,1,0,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(1,4,40,1,1,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(1,5,40,1,0,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(1,6,0.36,0,0,0);

INSERT INTO tb_FORMULATION (COEFFICIENT,DESCRIPTION,PRODUCT_ID) VALUES(1000,'LEITE EM PO DESNATADO',8);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(2,2,9285,0,0,1);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(2,3,40,1,0,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(2,4,40,1,1,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(2,5,40,1,0,0);
INSERT INTO tb_FORMULATION_ITEMS(FORMULATION_ID,PRODUCT_ID,QUANTITY,ROUND,TYPE,RAW_MATERIAL)VALUES(2,6,0.36,0,0,0);

INSERT INTO tb_EMPLOYEE(NAME,SECTOR_ID) VALUES('JOAO',1);
INSERT INTO tb_EMPLOYEE(NAME,SECTOR_ID) VALUES('SEBASTIAO',1);
INSERT INTO tb_EMPLOYEE(NAME,SECTOR_ID) VALUES('MARIA',2);
INSERT INTO tb_EMPLOYEE(NAME,SECTOR_ID) VALUES('ANA',2);
INSERT INTO tb_EMPLOYEE(NAME,SECTOR_ID) VALUES('JONAS',3);

INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(1,1);
INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(1,2);
INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(1,3);

INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(2,1);
INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(2,2);
INSERT INTO tb_FORMULATION_APPORTIONMENT(FORMULATION_ID,APPORTIONMENT_TYPE_ID) VALUES(2,3);

INSERT INTO tb_FORMULATION_SECTOR(FORMULATION_ID,SECTOR_ID) VALUES(1,1);
INSERT INTO tb_FORMULATION_SECTOR(FORMULATION_ID,SECTOR_ID) VALUES(1,3);

INSERT INTO tb_FORMULATION_SECTOR(FORMULATION_ID,SECTOR_ID) VALUES(2,1);
INSERT INTO tb_FORMULATION_SECTOR(FORMULATION_ID,SECTOR_ID) VALUES(2,3);